# https://github.com/ARMmbed/mbedtls.git

all:
	$(MAKE) -C library
#	g++ $(CFLAGS) -o test -Iinclude -Llibrary test2.cpp -lmbedx509 -lmbedtls -lmbedcrypto

clean:
	$(MAKE) -C library clean
	rm -f test
